---
title: "Final Project"
author: "Matthew Roland, Jean Jimenez, Kelly Eng"
date: "2023-12-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rio)
library(tidyverse)
library(mongolite)
library(googlesheets4)
library(flextable)
```

## Importing the Data

```{r}
connection_string <- "mongodb+srv://teamandroid:O9sWUq5h7JMDioFk@cluster0.kk0rkpj.mongodb.net/"
collection <- mongo(collection="european_values", db="database", url=connection_string)

columns <- c("study", "wave", "uniqid", "year", "cntry_AN", "A001", "A002", "A003", "A004", "A005", "A006", "A008", "A170", "A040", "A065", "A066", "A068", "A165", "B008", "D001_B", "G007_35_B", "Y002", "E015", "E035", "E036", "E039", "E069_01", "E225", "F025", "F028", "F028B_WVS7", "F066_EVS5", "F034", "F050", "F051", "F053", "F054", "F063", "X001", "X003R", "G027A", "X007", "X011", "X013", "X025A_01", "X028", "X047_WVS7", "X047E_EVS5", "C002", "G052")

#giturl <- "https://github.com/Mattr5541/DATA_607_Final_Project/raw/main/EVS_WVS_Joint_rData_v4_0.rdata"

#data <- import(giturl)

projection <- paste0('{', paste0('"', columns, '": 1', collapse = ','), '}')
data <- collection$find(query = '{}', fields = projection)
```

### Importing Eurovision Dataset

```{r}

eurovision_id="1UUXinsHP4iDUwprM_KKEng4DBK2uC7Y1NdbnD1lmkSU"

eurovis_raw=read_sheet(eurovision_id, sheet="All Songs Ever")


```

## Preprocessing the Data

```{r}
#Selecting our variables of interest (go over this in case you want to add more variables or remove any more); also, I may try to integrate these changes into MongoDb, but that remains to be seen
#Some notes: Only waves 5 & 7 are integrated into this dataset; wave 5 refers to the EVS data and wave 7 refers to the WVS data; we may need to keep this in mind when we filter data and plan our analyses

##Here are the variables I chose to include: cntry_AN = abbreviated names for countries; A001 = Important in Life: Family; A002 = Important in Life: Friends; A003 = Important in Life: Leisure Time; A004 = Important in Life: Politics; A005 = Important in Life: Work; A006 = Important in Life: Religion; A008 = Feeling of happiness; A170 = Satisfaction with your life; A040 = Important child qualities: religious faith; A065 = Member: Belong to religious organization; A066 = belong to education, arts, music, or cultural activities; A068 = Belong to political parties; A165 = Most people can be trusted; B008 = Protecting environment vs. economic growth; ; D001_B = Trust your family; G007_35_B = Trust: People of another religion; Y002 = Post-Materialist Index Score; E015 = Future changes: Less importance placed on work; E035 = Income inequality; E036 = Private vs State ownership of business; E039 = Competition good or harmful; E069_01 = Confidence: Churches; E225: Democracy: Religious authorities interpret the laws; F025 = Religious denomination; F028 = How often do you attend religious services; F028B_WVS7 = How often do you pray; F066_EVS5 = Pray to God outside of religious services; F034 = Religious person; F050 = Believe in God; F051 = Believe in: life after death; F053 = Believe in: hell; F054 - Believe in: heaven; F063 - How important is God in your life; X001 - Sex; X003R - Age recoded (6 intervals); G027A - Respondent immigrant / born in country; X007 - Marital status; X011 - How many children do you have; X013 - Number of people in household; X025A_01 - Highest educational level attained; X028 - Employment status Respondent; X047_WVS7 - Scale of incomes (WVS7); X047E_EVS5 - Scale of incomes (EVS5); C002 - Jobs scarce: Employers should give priority to (nation) people than immigrants; G052 - Evaluate the impact of immigrants on the development of [your country]

ews <- data[, !names(data) %in% "_id"]

#Belgium, Liechtenstein, Luxembourg, Monaco, Malta, San Marino were not included in the dataset; Note: CH denotes Switzerland; HR denotes Croatia
#Regions were defined in accordance with UN geoscheme classification (although I decided to add in Great Britain to Western Europe, following the CIA classification system, just as a matter of convenience. Let me know if there's a better way to go about this)
ews <- ews %>% filter(cntry_AN %in% c("AT", "FR", "DE", "NL", "CH", "GB", "AL", "AD", "BA", "HR", "CY", "GR", "IT", "ME", "MK", "PT", "RS", "SI", "ES", "US"))

ews <- ews %>% mutate(region = ifelse(cntry_AN %in% c("AT", "FR", "DE", "NL", "CH", "GB"), "Western Europe", "Southern Europe"))

ews <- ews %>% mutate(region = if_else(cntry_AN == "US", "America", region))

##And now I can clean the data
#First, I'll start by removing all values that denote a participant's uncertainty or refusal to answer question items; Items coded -1 -- -5 are considered missing, or instances in which the participant did not answer; -4 represents instances in which the question was not included in the survey (i.e., the question was included in the EVS survey, but not the EWS survey. As a result, I will keep it in for now, since its removal will lead to too much systematic data loss; we can handle those situations by simply excluding wave 5 or 7 from certain analyses/graphs)
ews <- ews %>% mutate_all(~ ifelse(. %in% c(-1, -2, -3, -5), NA, .))
ews <- drop_na(ews)
```

## Creating a Modified Dataset Representing Mean Values by Country

```{r}
ews_group <- ews %>% group_by(cntry_AN) %>% summarize(Family = mean(A001), Friends = mean(A002), Leisure = mean(A003), Politics = mean(A004), Work = mean(A005), Religion = mean(A006), Happiness = mean(A008), Satisfaction = mean(A170), Religious_Children = mean(A040), Organized_Religion = mean(A065), Cultural_Activities = mean(A066), Political_Party_Affiliation = mean(A068), Trust_People = mean(A165), Protect_Environment_vs_Economy = mean(B008), Trust_Family = mean(D001_B), Trust_Religion = mean(G007_35_B), Materialism = mean(Y002), Future_Change_Less_Work = mean(E015), Income_Inequality = mean(E035), Business_Ownership = mean(E036), Competition = mean(E039), Confidence_Church = mean(E069_01), Democracy_Religion = mean(E225), Deonomnation = mean(F025), Religious_Service_Attendance = mean(F025), Pray = mean(F028B_WVS7), Pray_Outside_Service = mean(F066_EVS5), Religious = mean(F034), Belivie_in_God = mean(F050), Belive_in_Afterlife = mean(F051), Belive_in_Hell = mean(F053), Believe_in_Heaven = mean(F054), Job_Priority_to_Immigrants = mean(C002), Impact_of_Immigration = mean(G052))
```

### Preprocessing Eurovision Data

```{r}
names(eurovis_raw)


semiclean_eurovis = eurovis_raw %>%
  select(Country, Year, Language, `Grand Final Points`,`Grand Final Place`) %>%
  filter(Year >= 2017, Year <= 2022)

semiclean_eurovis$`Grand Final Points`=as.numeric(unlist(semiclean_eurovis$`Grand Final Points`))

semiclean_eurovis$`Grand Final Place`=as.numeric(unlist(semiclean_eurovis$`Grand Final Place`))

names(semiclean_eurovis)=c("country","year","lang","pts","place")


```

## Initial Data Visualization and Exploration

### Eurovision Data

```{r}
#Visualizing Countries with most Gold, Silver, and bronze medals

most_gsb=semiclean_eurovis %>%
  group_by(year) %>%
  filter(place==1| place ==2| place == 3) %>%
  ungroup()%>%
  group_by(country)%>%
  summarise(count = n()) %>%
  arrange(desc(count))

ft_gsb1= flextable(most_gsb)

ft_gsb2 = ft_gsb1 |> 
  set_header_labels(country = "Nation", count = "Number of Eurovision Medals")  |>
  add_header_row(values = "Table of Eurovison Medals by Country 2017-2022", colwidths = 2) 

ft_gsb2
  
```
```{r}
#Visualizing Language Distributions

eurovis_langs= semiclean_eurovis %>%
  group_by(lang) %>%
  mutate(first_lang=sapply(strsplit(lang, ", "), `[`, 1)) %>%
  ungroup()%>%
  group_by(first_lang) %>%
  summarise(count=n()) %>%
  arrange(desc(count))

total_songs=eurovis_langs %>%
  summarise(result=sum(count))

langs=flextable(eurovis_langs)|> 
  set_header_labels(first_lang = "Song Performed First Language", count = "Number")  |>
  add_header_row(values = "Table of Eurovison Song First Language", colwidths = 2)

langs

eurolang_hist=ggplot(eurovis_langs, aes(x = first_lang, y = count)) +
  geom_bar(stat = "identity", fill = "blue") +
  theme_minimal() +
  labs(x = "Language", y = "Count", title = "Histogram of Eurovision Song First Language 2017-2022") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

eurolang_hist

```

```{r}
#Determining Winning Languages pts

lang_pts=semiclean_eurovis %>%
  group_by(year) %>%
  filter(place==1| place ==2| place == 3) %>%
  ungroup()%>%
  group_by(lang) %>%
  mutate(first_lang=sapply(strsplit(lang, ", "), `[`, 1)) %>%
  ungroup()%>%
  group_by(first_lang) %>%
  summarise(agg_pts=sum(pts, na.rm= TRUE))

lang_pt_tbl=flextable(lang_pts)|> 
  set_header_labels(first_lang = "Song Performed First Language", agg_pts = "Aggregated Points")  |>
  add_header_row(values = "Table of Eurovision 1st, 2nd, or 3rd Place Points by Language 2017-2022", colwidths = 2)

lang_pt_tbl


lang_pts_hist=ggplot(lang_pts, aes(x = first_lang, y = agg_pts)) +
  geom_bar(stat = "identity", fill = "blue") +
  theme_minimal() +
  labs(x = "Language", y = "Aggregated Points", title = "Histogram of Eurovision 1st, 2nd, or 3rd Place Points by Language 2017-2022") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

lang_pts_hist


```


```{r}
#Visualizing time distribution of Languages
lang_time=semiclean_eurovis %>%
  group_by(year) %>%
  filter(place==1| place ==2| place == 3) %>%
  ungroup()%>%
  group_by(lang) %>%
  mutate(first_lang=sapply(strsplit(lang, ", "), `[`, 1)) %>%
  ungroup()%>%
  group_by(year, first_lang) %>%
  summarise(count = n(), .groups = 'drop') %>%
  arrange(year, desc(count))


lang_time_tbl=flextable(lang_time)|> 
  set_header_labels(year="Year", first_lang = "Song Performed First Language", count = "Count")  |>
  add_header_row(values = "Table of Eurovision 1st, 2nd, or 3rd Place Points by Language and Year 2017-2022", colwidths = 3)

lang_time_tbl

```





```{r}
#Visualizing Point Distributions by Country
eurovis_pts= semiclean_eurovis %>%
  group_by(country) %>%
  summarise(agg_pts=sum(pts, na.rm= TRUE)) %>%
  arrange(desc(agg_pts))


pts_tab=flextable(eurovis_pts)|> 
  set_header_labels(country = "Country", agg_pts = "Aggregated Eurovision Points")  |>
  add_header_row(values = "Table of Aggregated Eurovison Points by Country 2017-2022", colwidths = 2)

pts_tab

europts_hist=ggplot(eurovis_pts, aes(x = country, y = agg_pts)) +
  geom_bar(stat = "identity", fill = "blue") +
  theme_minimal() +
  labs(x = "Country", y = "Total Points", title = "Histogram of Aggregated Eurovision Points by Country 2017-2022") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

europts_hist
```

